"""empty message

Revision ID: 359376048c09
Revises: 9eb9e6ddc119
Create Date: 2022-11-09 11:59:04.052981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '359376048c09'
down_revision = '9eb9e6ddc119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
